# BUILD STAGE
# Use the latest version of Node.js
From node:24-alpine AS build

# Set the working directory inside the container
WORKDIR /app

# Cài build tools (esbuild cần)
RUN apk add --no-cache python3 make g++ git

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application files
COPY . .

# build frontend
RUN npm run build

# PRODUCTION STAGE
FROM nginx:stable-alpine AS production
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]